<?php
/**
 * CurrentRMS Report Builder - API Configuration
 *
 * Configure your CurrentRMS API credentials here.
 * Get these from System Setup > Integrations > API in CurrentRMS.
 *
 * This file is auto-generated by the installer.
 * You can manually edit these values if needed.
 */

return [
    // Your CurrentRMS subdomain (e.g., 'mycompany' from mycompany.current-rms.com)
    'subdomain' => '',

    // Your API token from CurrentRMS (System Setup > Integrations > API)
    'api_token' => '',

    // API base URL (do not change unless instructed)
    'base_url' => 'https://api.current-rms.com/api/v1',

    // Request timeout in seconds
    'timeout' => 30,

    // Verify SSL certificates (set to false only for debugging)
    'verify_ssl' => true,
];
