<?php
/**
 * CurrentRMS Report Builder - Database Configuration
 *
 * Configure your database connection settings here.
 * This file is auto-generated by the installer.
 * You can manually edit these values if needed.
 */

return [
    'driver' => 'mysql',
    'host' => 'localhost',
    'port' => '3306',
    'database' => 'currentrms_reports',
    'username' => '',
    'password' => '',
    'charset' => 'utf8mb4',
    'collation' => 'utf8mb4_unicode_ci',
    'prefix' => 'crms_',
];
