<?php
/**
 * Pre-built Report Templates
 * Provides quick access to common business reports
 */

class ReportTemplates
{
    /**
     * Get all available report templates
     */
    public static function getAll(): array
    {
        return [
            'product_revenue' => [
                'name' => 'Product Revenue Report',
                'description' => 'Shows total revenue generated by each product from opportunities',
                'icon' => 'trending-up',
                'category' => 'Revenue',
                'module' => 'products',
                'columns' => ['id', 'name', 'product_group_name', 'rental_rate', 'sale_price'],
                'filters' => [],
                'sorting' => ['field' => 'name', 'direction' => 'asc'],
            ],
            'product_utilisation' => [
                'name' => 'Product Utilisation Report',
                'description' => 'Shows stock levels, availability, and booking rates for products',
                'icon' => 'bar-chart-2',
                'category' => 'Inventory',
                'module' => 'stock_levels',
                'columns' => ['product_name', 'store_name', 'quantity', 'quantity_available', 'quantity_booked', 'quantity_sub_rent', 'quantity_quarantined'],
                'filters' => [],
                'sorting' => ['field' => 'product_name', 'direction' => 'asc'],
            ],
            'customer_revenue' => [
                'name' => 'Customer Revenue Report',
                'description' => 'Shows revenue and balance by customer/member',
                'icon' => 'users',
                'category' => 'Revenue',
                'module' => 'members',
                'columns' => ['id', 'name', 'company', 'email', 'phone', 'balance'],
                'filters' => [],
                'sorting' => ['field' => 'name', 'direction' => 'asc'],
            ],
            'monthly_revenue' => [
                'name' => 'Monthly Invoice Summary',
                'description' => 'Shows all invoices with totals, useful for monthly revenue analysis',
                'icon' => 'calendar',
                'category' => 'Revenue',
                'module' => 'invoices',
                'columns' => ['number', 'member_name', 'invoice_date', 'due_date', 'subtotal', 'tax_total', 'total', 'amount_paid', 'balance', 'state'],
                'filters' => [],
                'sorting' => ['field' => 'invoice_date', 'direction' => 'desc'],
            ],
            'outstanding_invoices' => [
                'name' => 'Outstanding Invoices',
                'description' => 'Shows all unpaid invoices with balances due',
                'icon' => 'alert-circle',
                'category' => 'Finance',
                'module' => 'invoices',
                'columns' => ['number', 'member_name', 'invoice_date', 'due_date', 'total', 'amount_paid', 'balance', 'state'],
                'filters' => [
                    ['field' => 'state', 'predicate' => 'eq', 'value' => 'sent'],
                ],
                'sorting' => ['field' => 'due_date', 'direction' => 'asc'],
            ],
            'opportunity_pipeline' => [
                'name' => 'Opportunity Pipeline',
                'description' => 'Shows all active opportunities with values and status',
                'icon' => 'git-branch',
                'category' => 'Sales',
                'module' => 'opportunities',
                'columns' => ['id', 'subject', 'member_name', 'venue_name', 'status', 'starts_at', 'ends_at', 'charge_total', 'tax_total', 'grand_total'],
                'filters' => [],
                'sorting' => ['field' => 'starts_at', 'direction' => 'asc'],
            ],
            'upcoming_opportunities' => [
                'name' => 'Upcoming Events',
                'description' => 'Shows opportunities starting in the next 30 days',
                'icon' => 'clock',
                'category' => 'Operations',
                'module' => 'opportunities',
                'columns' => ['subject', 'member_name', 'venue_name', 'status', 'starts_at', 'ends_at', 'grand_total'],
                'filters' => [
                    ['field' => 'starts_at', 'predicate' => 'gteq', 'value' => date('Y-m-d')],
                    ['field' => 'starts_at', 'predicate' => 'lteq', 'value' => date('Y-m-d', strtotime('+30 days'))],
                ],
                'sorting' => ['field' => 'starts_at', 'direction' => 'asc'],
            ],
            'stock_availability' => [
                'name' => 'Stock Availability',
                'description' => 'Shows current stock levels across all stores',
                'icon' => 'package',
                'category' => 'Inventory',
                'module' => 'stock_levels',
                'columns' => ['product_name', 'store_name', 'quantity', 'quantity_available', 'quantity_booked'],
                'filters' => [],
                'sorting' => ['field' => 'quantity_available', 'direction' => 'asc'],
            ],
            'low_stock_alert' => [
                'name' => 'Low Stock Alert',
                'description' => 'Shows items with low availability (less than 5 available)',
                'icon' => 'alert-triangle',
                'category' => 'Inventory',
                'module' => 'stock_levels',
                'columns' => ['product_name', 'store_name', 'quantity', 'quantity_available', 'quantity_booked', 'quantity_quarantined'],
                'filters' => [
                    ['field' => 'quantity_available', 'predicate' => 'lt', 'value' => '5'],
                ],
                'sorting' => ['field' => 'quantity_available', 'direction' => 'asc'],
            ],
            'quarantined_items' => [
                'name' => 'Quarantined Items',
                'description' => 'Shows all items currently in quarantine with reasons',
                'icon' => 'x-circle',
                'category' => 'Inventory',
                'module' => 'quarantines',
                'columns' => ['item_name', 'store_name', 'quantity', 'reason', 'created_at'],
                'filters' => [],
                'sorting' => ['field' => 'created_at', 'direction' => 'desc'],
            ],
            'purchase_orders' => [
                'name' => 'Purchase Orders Summary',
                'description' => 'Shows all purchase orders with suppliers and totals',
                'icon' => 'shopping-cart',
                'category' => 'Procurement',
                'module' => 'purchase_orders',
                'columns' => ['number', 'supplier_name', 'order_date', 'expected_date', 'subtotal', 'tax_total', 'total', 'state'],
                'filters' => [],
                'sorting' => ['field' => 'order_date', 'direction' => 'desc'],
            ],
            'project_overview' => [
                'name' => 'Project Overview',
                'description' => 'Shows all projects with budgets and revenue',
                'icon' => 'folder',
                'category' => 'Operations',
                'module' => 'projects',
                'columns' => ['id', 'name', 'member_name', 'status', 'budget', 'revenue', 'starts_at', 'ends_at'],
                'filters' => [],
                'sorting' => ['field' => 'starts_at', 'direction' => 'desc'],
            ],
        ];
    }

    /**
     * Get a specific template by key
     */
    public static function get(string $key): ?array
    {
        $templates = self::getAll();
        return $templates[$key] ?? null;
    }

    /**
     * Get templates by category
     */
    public static function getByCategory(string $category): array
    {
        return array_filter(self::getAll(), fn($t) => $t['category'] === $category);
    }

    /**
     * Get all unique categories
     */
    public static function getCategories(): array
    {
        $categories = array_unique(array_column(self::getAll(), 'category'));
        sort($categories);
        return $categories;
    }

    /**
     * Get templates for a specific module
     */
    public static function getForModule(string $module): array
    {
        return array_filter(self::getAll(), fn($t) => $t['module'] === $module);
    }
}
